### ISSUE TITLE
Client Allocation Request for: This is an organization

### ISSUE THREAD

**Issue by tikagan** [data-preservation-programs/filplus-general-application-test#19]
# Client Allocation Questions

## Core Information
- Name: This is an organization
- Website / Social Media: [https://organization-website.com](https://organization-website.com), (@organization, Twitter)
- Region: Asia excl. Greater China
- DataCap Requested: 69 GiB
- Addresses to be Notarized: f27182818284590452353602874
- Notary Requested: Simon

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
