### ISSUE TITLE
Client Allocation Request for: Org Inc.

### ISSUE THREAD

**Issue by tikagan** [data-preservation-programs/filplus-general-application-test#21]
# Client Allocation Questions

## Core Information
- Name: Org Inc.
- Website / Social Media: [https:org-inc.com](https:org-inc.com), (@org-inc, Twitter)
- Region: Asia excl. GCN
- DataCap Requested: 420 GiB
- Addresses to be Notarized: f27182818284590452353602874
- Notary Requested: Suki

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
