### ISSUE TITLE
Client Allocation Request for: pfyg

### ISSUE THREAD

**Issue by tikagan** [data-preservation-programs/filplus-general-application-test#29]
# Client Allocation Questions

## Core Information
- Name: pfyg
- Website / Social Media: [pyfg](pyfg), (@pyfg, Twitter)
- Region: Greater China
- DataCap Requested: 32 GiB
- Addresses to be Notarized: f27182818284590452353602874
- Notary Requested: Fenbushi Capital

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
