### ISSUE TITLE
Client Allocation Request for: pyfg

### ISSUE THREAD

**Issue by tikagan** [data-preservation-programs/filplus-general-application-test#32]
# Client Allocation Questions

## Core Information
- Name: pyfg
- Website / Social Media: [pyfg.com](pyfg.com), (@pyfg, Twitter)
- Region: Europe
- DataCap Requested: 192 GiB
- Addresses to be Notarized: f27182818284590452353602874
- Notary Requested: BingHe Web3.0 Lab

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
