### ISSUE TITLE
Client Allocation Request for: gcrl

### ISSUE THREAD

**Issue by tikagan** [data-preservation-programs/filplus-general-application-test#40]
# Client Allocation Questions

## Core Information
- Name: gcrl
- Website / Social Media: [gcrl.com](gcrl.com), (@gcrl, Twitter)
- Region: North America
- DataCap Requested: 96 GiB
- Addresses to be Notarized: f14142135623730950488016887
- Notary Requested: Coffee Cloud

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
