### ISSUE TITLE
Client Allocation Request for: oeib

### ISSUE THREAD

**Issue by tikagan** [data-preservation-programs/filplus-general-application-test#41]
# Client Allocation Questions

## Core Information
- Name: oeib
- Website / Social Media: [eoiub](eoiub), (oeib, eo)
- Region: Oceania
- DataCap Requested: 128 GiB
- Addresses to be Notarized: f14142135623730950488016887
- Notary Requested: Sounghwan Park

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
