### ISSUE TITLE
Client Allocation Request for: AOE Inc

### ISSUE THREAD

**Issue by tikagan** [data-preservation-programs/filplus-general-application-test#6]
# Client Allocation Questions

## Core Information
- Name: AOE Inc
- Website / Social Media: [https://aoe.com](https://aoe.com), (@aoe, Twitter)
- Region: Oceania
- DataCap Requested: 32 GiB
- Addresses to be Notarized: f1495978707
- Notary Requested: BingHe Web3.0 Lab

**Comment by data-programs** [comment]
<img width="32" alt="KYC" Verified src="https://stable.filplus.storage/images/filplus-kyc-verified-badge.png"/>

This user’s identity has been verified through [filplus.storage](https://filplus.storage)
